<?php
/**
 * @file
 * Code for the Accordion feature.
 */

include_once 'accordion.features.inc';


function accordion_theme($existing, $type, $theme, $path) {
  return array(
    'field__field_accrodion' => array(
      'render element' => 'content',
      'base hook' => 'field',
      'template' => 'accordion-field-accordion',
      ),
    );
}

function accordion_preprocess_fieldable_panels_pane(&$vars) {
  switch ($vars['elements']['#bundle']) {
    case 'accordion':
      drupal_add_library('system', 'ui.accordion');
      drupal_add_css(drupal_get_path('module','accordion').'/accordion.css');
      drupal_add_js(drupal_get_path('module','accordion').'/accordion.js');
    break;
  }
}
